[package]
version = "0.1.0"
name = "btc-core-hash-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = "3.0.0-rc4"
bitcoin-core-rs = { path = "../bitcoin-core-rs"}